version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"   # RabbitMQ communication port
      - "15672:15672" # RabbitMQ web management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
